
package com.unipago.pruebadesarrollador.client.employee;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://service.pruebadesarrollador.unipago.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.unipago.pruebadesarrollador.client.employee.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.FindResponse")
    public Employee find(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.unipago.pruebadesarrollador.client.employee.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.FindAllResponse")
    public List<Employee> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.unipago.pruebadesarrollador.client.employee.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", className = "com.unipago.pruebadesarrollador.client.employee.SaveResponse")
    public Employee save(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

}
