
package com.unipago.pruebadesarrollador.client.department;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DepartmentService", targetNamespace = "http://service.pruebadesarrollador.unipago.com/", wsdlLocation = "http://localhost:8080/servicioweb/DepartmentService?wsdl")
public class DepartmentService_Service
    extends Service
{

    private final static URL DEPARTMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEPARTMENTSERVICE_EXCEPTION;
    private final static QName DEPARTMENTSERVICE_QNAME = new QName("http://service.pruebadesarrollador.unipago.com/", "DepartmentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servicioweb/DepartmentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEPARTMENTSERVICE_WSDL_LOCATION = url;
        DEPARTMENTSERVICE_EXCEPTION = e;
    }

    public DepartmentService_Service() {
        super(__getWsdlLocation(), DEPARTMENTSERVICE_QNAME);
    }

    public DepartmentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPARTMENTSERVICE_QNAME, features);
    }

    public DepartmentService_Service(URL wsdlLocation) {
        super(wsdlLocation, DEPARTMENTSERVICE_QNAME);
    }

    public DepartmentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPARTMENTSERVICE_QNAME, features);
    }

    public DepartmentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartmentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DepartmentService
     */
    @WebEndpoint(name = "DepartmentServicePort")
    public DepartmentService getDepartmentServicePort() {
        return super.getPort(new QName("http://service.pruebadesarrollador.unipago.com/", "DepartmentServicePort"), DepartmentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepartmentService
     */
    @WebEndpoint(name = "DepartmentServicePort")
    public DepartmentService getDepartmentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.pruebadesarrollador.unipago.com/", "DepartmentServicePort"), DepartmentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPARTMENTSERVICE_EXCEPTION!= null) {
            throw DEPARTMENTSERVICE_EXCEPTION;
        }
        return DEPARTMENTSERVICE_WSDL_LOCATION;
    }

}
